name: Build and Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vets-and-lints:
    name: Vets and Lints
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
          node-version: '14.x'
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'
    - uses: actions/setup-go@v5
      with:
          go-version: '^1.14'
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './scripts'
    - name: Install front-end and run test/fmt checks
      run: |
        cd frontend
        yarn
        yarn fmt -c
        yarn test
    - name: Install go tools
      run: |
        scripts/install_tools.sh
    - name: Run generation
      run: |
        scripts/generate.sh
    - name: Vet go code
      run: |
        # Check formatting
        test -z "$(goimports -l . | tee /dev/stderr)"
        # vet
        go vet ./...
        golangci-lint run --build-tags production
  go-tests:
    name: Go tests & building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
          node-version: '14.x'
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'
    - uses: actions/setup-go@v5
      with:
          go-version: '^1.14'
    - name: Install front-end
      run: |
        cd frontend
        yarn
    - name: Install go tools
      run: |
        scripts/install_tools.sh
    - name: Run generation
      run: |
        scripts/generate.sh
    - name: Run go tests
      run: |
        # test
        scripts/test.sh
    - name: Try building in production mode
      run: |
        scripts/production_build.sh
