name: Publish to Docker Hub (stable)
on:
  release:
    types: [created]
jobs:
  latest:
    name: Full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Prepare version tags
        run: echo ${{ github.ref }} | xargs basename | echo ::set-env name=VERS::$(awk -F "." '{ print $1 "," $1 "." $2 "," $1 "." $2 "." $3 }')
      - name: Publish
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: natsukagami/kjudge
          tags: ${{ env.VERS }},latest
          dockerfile: ./docker/Dockerfile
  latest-gcc:
    name: GCC-only
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Prepare version tags
        run: echo ${{ github.ref }} | xargs basename | echo ::set-env name=VERS_GCC::$(awk -F "." '{ print $1 "," $1 "." $2 "," $1 "." $2 "." $3 }' | sed -E 's/(,|$)/-gcc\1/g')
      - name: Publish
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: natsukagami/kjudge
          tags: ${{ env.VERS_GCC }},latest-gcc
          dockerfile: ./docker/gcc-only.dockerfile
